displayName=Wine to 99
author=sailo
description=Tracks successful wines remaining to 99 Cooking, fermenting wines, and session rates
tags=wine,cooking,ferment,fermenting,xp,experience,99,skilling,tracker
version=
plugins=com.winetoninetynine.WineTo99Plugin
build=standard
